- name: .github/workflows/build.yml
  format: text
  includes:
  - .github/workflows/build.yml
  ignore: true
- name: .github/workflows/codeql-analysis.yml
  format: text
  includes:
  - .github/workflows/codeql-analysis.yml
  delete: true
