- name: ignore-files
  format: text
  includes:
  - .github/workflows/build.yml
  ignore: true
- name: delete-redundant-files
  format: text
  includes:
  - .github/workflows/codeql-analysis.yml
  - .github/release-drafter.yml
  delete: true
