repositories:
- remal-gradle-plugins/gradle-api

transformations:
- name: delete-redundant-files
  format: text
  includes:
  - .github/workflows/codeql-analysis.yml
  - .github/workflows/release-drafter.yml
  - .github/release-drafter.yml
  delete: true
- name: ignore-files
  format: text
  includes:
  - .github/workflows/build.yml
  ignore: true
- name: mergify
  format: text
  includes:
  - .mergify/config.yml
  script: |
    return content
        .replaceAll(/(`)build\1/g, '$1build-success$1')
        .replaceAll(/(=\s*)build('|\n|$)/g, '$1build-success$2')
