# Configuration file for Mergify GitHub App: https://github.com/marketplace/mergify

# All Status Checks should be listed explicitly (see https://doc.mergify.io/conditions.html#validating-all-status-check):
#   `WIP` - https://github.com/marketplace/wip

pull_request_rules:
- name: Auto merge approved
  conditions:
  - '#approved-reviews-by>=1'
  - -conflict
  - -closed
  - -merged
  - -draft
  - -locked
  - '#changes-requested-reviews-by=0'
  - status-success=WIP
  - '#status-neutral=0'
  - '#status-failure=0'
  actions:
    merge:
      method: squash

- name: Auto approve dependency updates
  conditions:
  - '#approved-reviews-by=0'
  - author~=^(dependabot(-preview)?|renovate)\[bot\]$
  - 'check-neutral!=renovate/stability-days'
  - 'check-pending!=renovate/stability-days'
  - 'check-failure!=renovate/stability-days'
  - -closed
  - -merged
  actions:
    review:
      message: 'Approved automatically by @Mergifyio.'
